### ISSUE TITLE
Pipeline failed for base

### ISSUE THREAD

**Issue by Taknok** [GriffinPlus/docker-base#1]
Since January 2022, the pipeline has failed for the base image.
> Could not fetch access token for Azure. Verify if the Service Principal used is valid and not expired.

https://dev.azure.com/griffinplus/Docker%20Images/_build/results?buildId=6094&view=results

**Comment by ravenpride** [comment]
Hi @Taknok, thank you for the hint. I've fixed it and the pipelines run just fine again now.
